# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pkmidicron/mainwindow.ui'
#
# Created: Wed Oct 22 19:18:00 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outerSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.outerSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.outerSplitter.setObjectName("outerSplitter")
        self.bindingsList = BindingListWidget(self.outerSplitter)
        self.bindingsList.setMinimumSize(QtCore.QSize(200, 0))
        self.bindingsList.setObjectName("bindingsList")
        self.innerSplitter = QtWidgets.QSplitter(self.outerSplitter)
        self.innerSplitter.setOrientation(QtCore.Qt.Vertical)
        self.innerSplitter.setObjectName("innerSplitter")
        self.simulatorTabs = QtWidgets.QTabWidget(self.innerSplitter)
        self.simulatorTabs.setObjectName("simulatorTabs")
        self.simulator = Simulator()
        self.simulator.setObjectName("simulator")
        self.simulatorTabs.addTab(self.simulator, "")
        self.activityLog = QtWidgets.QTableWidget(self.innerSplitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.activityLog.setFont(font)
        self.activityLog.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.activityLog.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.activityLog.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.activityLog.setShowGrid(False)
        self.activityLog.setObjectName("activityLog")
        self.activityLog.setColumnCount(5)
        self.activityLog.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(4, item)
        self.activityLog.horizontalHeader().setDefaultSectionSize(100)
        self.activityLog.horizontalHeader().setHighlightSections(False)
        self.activityLog.horizontalHeader().setMinimumSectionSize(2)
        self.activityLog.horizontalHeader().setStretchLastSection(True)
        self.activityLog.verticalHeader().setVisible(False)
        self.activityLog.verticalHeader().setDefaultSectionSize(15)
        self.activityLog.verticalHeader().setMinimumSectionSize(15)
        self.bindingScroller = QtWidgets.QScrollArea(self.innerSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bindingScroller.sizePolicy().hasHeightForWidth())
        self.bindingScroller.setSizePolicy(sizePolicy)
        self.bindingScroller.setWidgetResizable(True)
        self.bindingScroller.setObjectName("bindingScroller")
        self.bindingProperties = BindingProperties()
        self.bindingProperties.setGeometry(QtCore.QRect(0, 0, 332, 278))
        self.bindingProperties.setObjectName("bindingProperties")
        self.bindingScroller.setWidget(self.bindingProperties)
        self.verticalLayout.addWidget(self.outerSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSimulator = QtWidgets.QAction(MainWindow)
        self.actionSimulator.setObjectName("actionSimulator")
        self.actionActivity_Log = QtWidgets.QAction(MainWindow)
        self.actionActivity_Log.setObjectName("actionActivity_Log")
        self.actionBindings = QtWidgets.QAction(MainWindow)
        self.actionBindings.setObjectName("actionBindings")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionAbout)
        self.menuView.addAction(self.actionSimulator)
        self.menuView.addAction(self.actionActivity_Log)
        self.menuView.addAction(self.actionBindings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PKMidiCron"))
        item = self.activityLog.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.activityLog.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Port"))
        item = self.activityLog.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.activityLog.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Channel"))
        item = self.activityLog.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save..."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "S&ave As"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSimulator.setText(_translate("MainWindow", "Simulator"))
        self.actionActivity_Log.setText(_translate("MainWindow", "Activity Log"))
        self.actionBindings.setText(_translate("MainWindow", "Bindings"))

from .bindinglistwidget import BindingListWidget
from .bindingproperties import BindingProperties
from .simulator import Simulator
