# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pkmidicron/mainwindow.ui'
#
# Created: Sun Nov 23 19:05:03 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outerSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.outerSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.outerSplitter.setObjectName("outerSplitter")
        self.bindingsList = ListWidget(self.outerSplitter)
        self.bindingsList.setMinimumSize(QtCore.QSize(200, 0))
        self.bindingsList.setObjectName("bindingsList")
        self.innerSplitter = QtWidgets.QSplitter(self.outerSplitter)
        self.innerSplitter.setOrientation(QtCore.Qt.Vertical)
        self.innerSplitter.setObjectName("innerSplitter")
        self.simulator = Simulator(self.innerSplitter)
        self.simulator.setObjectName("simulator")
        self.activityLog = QtWidgets.QTableWidget(self.innerSplitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.activityLog.setFont(font)
        self.activityLog.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.activityLog.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.activityLog.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.activityLog.setShowGrid(False)
        self.activityLog.setObjectName("activityLog")
        self.activityLog.setColumnCount(5)
        self.activityLog.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityLog.setHorizontalHeaderItem(4, item)
        self.activityLog.horizontalHeader().setDefaultSectionSize(100)
        self.activityLog.horizontalHeader().setHighlightSections(False)
        self.activityLog.horizontalHeader().setMinimumSectionSize(2)
        self.activityLog.horizontalHeader().setStretchLastSection(True)
        self.activityLog.verticalHeader().setVisible(False)
        self.activityLog.verticalHeader().setDefaultSectionSize(15)
        self.activityLog.verticalHeader().setMinimumSectionSize(15)
        self.bindingPropertiesScroller = ScrollArea(self.innerSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bindingPropertiesScroller.sizePolicy().hasHeightForWidth())
        self.bindingPropertiesScroller.setSizePolicy(sizePolicy)
        self.bindingPropertiesScroller.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.bindingPropertiesScroller.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bindingPropertiesScroller.setWidgetResizable(True)
        self.bindingPropertiesScroller.setObjectName("bindingPropertiesScroller")
        self.bindingProperties = BindingProperties()
        self.bindingProperties.setGeometry(QtCore.QRect(0, 0, 316, 295))
        self.bindingProperties.setObjectName("bindingProperties")
        self.bindingPropertiesScroller.setWidget(self.bindingProperties)
        self.verticalLayout.addWidget(self.outerSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionToggleSimulator = QtWidgets.QAction(MainWindow)
        self.actionToggleSimulator.setObjectName("actionToggleSimulator")
        self.actionToggleLog = QtWidgets.QAction(MainWindow)
        self.actionToggleLog.setObjectName("actionToggleLog")
        self.actionToggleBindingProperties = QtWidgets.QAction(MainWindow)
        self.actionToggleBindingProperties.setObjectName("actionToggleBindingProperties")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setMenuRole(QtWidgets.QAction.PreferencesRole)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAddBinding = QtWidgets.QAction(MainWindow)
        self.actionAddBinding.setObjectName("actionAddBinding")
        self.actionDeleteBinding = QtWidgets.QAction(MainWindow)
        self.actionDeleteBinding.setEnabled(False)
        self.actionDeleteBinding.setObjectName("actionDeleteBinding")
        self.actionClearLog = QtWidgets.QAction(MainWindow)
        self.actionClearLog.setEnabled(False)
        self.actionClearLog.setObjectName("actionClearLog")
        self.actionShowHelp = QtWidgets.QAction(MainWindow)
        self.actionShowHelp.setObjectName("actionShowHelp")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setShortcut("")
        self.actionExit.setObjectName("actionExit")
        self.actionGo_Home = QtWidgets.QAction(MainWindow)
        self.actionGo_Home.setObjectName("actionGo_Home")
        self.actionToggleMainWindow = QtWidgets.QAction(MainWindow)
        self.actionToggleMainWindow.setObjectName("actionToggleMainWindow")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionToggleMainWindow)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionToggleSimulator)
        self.menuView.addAction(self.actionToggleLog)
        self.menuView.addAction(self.actionToggleBindingProperties)
        self.menuEdit.addAction(self.actionAddBinding)
        self.menuEdit.addAction(self.actionDeleteBinding)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClearLog)
        self.menuHelp.addAction(self.actionShowHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionGo_Home)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PKMidiCron"))
        item = self.activityLog.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.activityLog.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Port"))
        item = self.activityLog.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.activityLog.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Channel"))
        item = self.activityLog.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save..."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "S&ave As"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionToggleSimulator.setText(_translate("MainWindow", "Simulator"))
        self.actionToggleSimulator.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionToggleLog.setText(_translate("MainWindow", "Activity Log"))
        self.actionToggleLog.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.actionToggleBindingProperties.setText(_translate("MainWindow", "Binding Properties"))
        self.actionToggleBindingProperties.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionAddBinding.setText(_translate("MainWindow", "Add Binding"))
        self.actionAddBinding.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionDeleteBinding.setText(_translate("MainWindow", "Delete Binding"))
        self.actionDeleteBinding.setShortcut(_translate("MainWindow", "Backspace"))
        self.actionClearLog.setText(_translate("MainWindow", "Clear Log"))
        self.actionClearLog.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.actionShowHelp.setText(_translate("MainWindow", "Show Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionGo_Home.setText(_translate("MainWindow", "Go Home"))
        self.actionGo_Home.setShortcut(_translate("MainWindow", "Ctrl+J, Ctrl+G"))
        self.actionToggleMainWindow.setText(_translate("MainWindow", "Main Window"))
        self.actionToggleMainWindow.setShortcut(_translate("MainWindow", "Ctrl+W"))

from .simulator import Simulator
from .util import ListWidget, ScrollArea
from .bindingproperties import BindingProperties
